[package]
name = "oblux"
version = "0.1.0"
edition = "2024"
description = "one-bit less unsigned primitives"
readme = "README.md"
repository = "https://github.com/rotorship/oblux"
license = "MIT OR Apache-2.0"

[dependencies]
